[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/review"
  to = "https://ai-code-review-backend-4b80.onrender.com/review"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/review/*"
  to = "https://ai-code-review-backend-4b80.onrender.com/review/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://ai-code-review-backend-4b80.onrender.com/health"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200